#python3 demo.py -b './' -c './config/' -d 'config' -v 'boar'
python3 demo.py -b './' -c './config/' -d 'config' -v 'explosion'
#python3 demo.py -b './' -c './config/' -d 'config' -v 'speech'
#python3 demo.py -b './' -c './config/' -d 'config' -v 'crying'
#python3 demo.py -b './' -c './config/' -d 'config' -v 'screaming'
